namespace: service-cloud
serviceName: sftpapi
initialReplica: 2
autoScale: true
image: odprod.azurecr.io/odprod/sftpapi
containerPort: 8080
healthPath: /sftpapi/status
gateway: service-cloud-gateway
context: /sftpapi
resources:
  limits:
    cpu: 1.5
    memory: "4Gi"
  requests:
    cpu: 0.75
    memory: "500Mi"
